/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsOption {
  enableTables: boolean
  enableFootnotes: boolean
  enableStrikethrough: boolean
  enableTasklists: boolean
  enableSmartPunctuation: boolean
  enableHeadingAttributes: boolean
  enableContainer: boolean
  enableMdx: boolean
  codeBlockTheme: string
}
export function transformNoHighlight(content: string, opts: JsOption): string
export function transform(content: string, opts: JsOption): string
